config/routes.rb
Rails.application.routes.draw do
  root'home#index'

  resources :questions do
    resources :answers
  end
  devise_for :users

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)


    if user.admin? 
        
        can :manage, :all 
    
    else

        can :update,Question do |question|
            question.user == user
        end

        can :destroy,Question do |question|
            question.user == user
        end

        can :destroy,Answer do |answer|
            answer.user == user
        end

        can :create,Question
        can :create,Answer


    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/answer.rb
class Answer < ActiveRecord::Base
	belongs_to :question
	belongs_to :user
end

app/models/question.rb
class Question < ActiveRecord::Base
	belongs_to :user
	has_many :answers
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :questions
	has_many :answers
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController

	def create
	  @question = Question.find(params[:question_id])
		@answer = @question.answers.build(answers_params)
		@answer.user = current_user
		@answer.save

		redirect_to questions_url
		
	end

	def destroy
		@question = Question.find(params[:question_id])
		@answer = @question.answers.find(params[:id]).destroy
		redirect_to questions_url
	end

	private

	  def answers_params
	  params.require(:answer).permit(:content)	
	  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  rescue_from CanCan::AccessDenied do |exception|
  	redirect_to questions_url, :alert => exception.message
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  	if user_signed_in?
  		redirect_to questions_path
    end
  end

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: [:show, :edit, :update, :destroy]

  # GET /questions
  # GET /questions.json
  def index
    @questions = Question.all
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
    authorize! :update, @question
  end

  # GET /questions/new
  def new
    @question = Question.new
  end

  # GET /questions/1/edit
  def edit
     authorize! :update, @question
  end

  # POST /questions
  # POST /questions.json
  def create
    @user = current_user
    @question = @user.questions.build(question_params)

    respond_to do |format|
      if @question.save
        format.html { redirect_to @question, notice: 'Question was successfully created.' }
        format.json { render :show, status: :created, location: @question }
      else
        format.html { render :new }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questions/1
  # PATCH/PUT /questions/1.json
  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to @question, notice: 'Question was successfully updated.' }
        format.json { render :show, status: :ok, location: @question }
      else
        format.html { render :edit }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question.destroy
    respond_to do |format|
      format.html { redirect_to questions_url, notice: 'Question was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def question_params
      params.require(:question).permit(:content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/answers/_answer.html.erb
<p><%= answer.content %> 
   <% if can? :destroy,answer %>
	:<%= link_to "Delete",question_answer_path(answer.question,answer),method: :delete,id: "linkd" %>
   <% end %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Myforum</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
 
    <% if user_signed_in? %>
      <h3 style="font-weight: bold; color: purple;">Welcome,<%= current_user.email %></h3>
      <%= link_to "Logout",destroy_user_session_path,method: :delete,class: 'btn btn-primary' %>
    <% else %>

     </br>
     </br>
     <div class="jumbotron">
     <h5> The Forum! </h5>
     </div>
      <p style="text-align: center;"><%= link_to "Sign In",new_user_session_path,class: 'btn btn-primary' %></p>
    <% end %>  
    
    <% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>">
    <%= message %>
  </div>
<% end %>
<%= yield %>

</body>
</html>

<script>
  
  $(".alert" ).delay(5000).slideUp(1000);

</script>

app/views/questions/_form.html.erb
<%= form_for(@question,html: { multipart: true, class: "form-horizontal" }) do |f| %>
  <% if @question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
      <% @question.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
  <div class = "col-md-3">
    <%= f.label :content %><br>
    <%= f.text_field :content ,class: 'form-control'%>
  </div>
  </div>
  <div class="form-group">
  <div class = "col-md-2">
    <%= f.submit class: 'btn btn-primary form-control' %>
  </div>
  </div>
<% end %>

app/views/questions/edit.html.erb
<h2 style="font-weight: bold;">Editing Question</h2>

<%= render 'form' %>

<%= link_to 'Show', @question,class: 'btn btn-success' %> |
<%= link_to 'Back', questions_path,class: 'btn btn-success' %>

app/views/questions/index.html.erb
<h1 style="font-weight: bold;">Forum</h1>
<%=link_to "New Question",new_question_path,class: 'btn btn-success' %>
<br>
<br>

<% @questions.each do |question| %>
  
  <div style="border: 1px solid black; background-color:#b9e4f7;">
               <h3 style="font-weight: bold;"><%= question.content %></h3>
               <%=  time_ago_in_words(question.created_at) %> ago by <%= question.user.email %>
               <br>
              <% if can? :update,question %>
                <%= link_to "Edit",edit_question_path(question),id: 'link' %> |
              <% end %>
              <% if can? :update,question %>
                <%= link_to "Destroy",question,method: :delete,data: {confirm: 'Are you sure?'},id: 'linkd'%>
                <% end %>

               <% if question.answers.any? %>
                 <h4 style="font-weight: bold;">Answers:</h4>

                 <%= render question.answers %>
               <% end %>

               <br>
               <p style="font-weight: bold;">Add Answer</p>
               <%= form_for ([question,question.answers.build]) do |f| %>
                 <%= f.text_area :content %>
                 <%= submit_tag "Add" ,class: 'btn btn-primary' %>
               <% end %>
    
  </div>

  <br>
  <br>

  <% end %>

app/views/questions/new.html.erb
<h1>New Question</h1>

<%= render 'form' %>

<%= link_to 'Back', questions_path,class: 'btn btn-success' %>

app/views/questions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @question.content %>
</p>

<%= link_to 'Edit', edit_question_path(@question) %> |
<%= link_to 'Back', questions_path %>